In [1]:
import torch

In [2]:
x = torch.Tensor(5, 3)
print x


1.00000e-21 *
  0.0000  0.0000  0.0109
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  1.9686  0.0000
  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]



In [3]:
x = torch.rand(5, 3)
print x


 0.1991  0.9964  0.3483
 0.7594  0.8520  0.6702
 0.6392  0.9526  0.0209
 0.9661  0.7654  0.1669
 0.9346  0.0336  0.2361
[torch.FloatTensor of size 5x3]



In [5]:
print x.size()

torch.Size([5, 3])


In [6]:
y = torch.rand(5, 3)
print x + y


 1.0805  1.4871  0.3711
 0.7917  1.4022  0.7712
 1.3067  1.1764  0.1086
 1.9332  1.7636  0.7973
 1.9091  0.1172  0.8921
[torch.FloatTensor of size 5x3]



In [7]:
print torch.add(x, y)


 1.0805  1.4871  0.3711
 0.7917  1.4022  0.7712
 1.3067  1.1764  0.1086
 1.9332  1.7636  0.7973
 1.9091  0.1172  0.8921
[torch.FloatTensor of size 5x3]



In [9]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print result


 1.0805  1.4871  0.3711
 0.7917  1.4022  0.7712
 1.3067  1.1764  0.1086
 1.9332  1.7636  0.7973
 1.9091  0.1172  0.8921
[torch.FloatTensor of size 5x3]



In [10]:
# inplace operation is post-fixed with an '_' (.copy_(), .t_()) 
y.add_(x)
print y


 1.0805  1.4871  0.3711
 0.7917  1.4022  0.7712
 1.3067  1.1764  0.1086
 1.9332  1.7636  0.7973
 1.9091  0.1172  0.8921
[torch.FloatTensor of size 5x3]



In [11]:
print x[:, 1]


 0.9964
 0.8520
 0.9526
 0.7654
 0.0336
[torch.FloatTensor of size 5]



In [13]:
# resize/reshape
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print x.size(), y.size(), z.size()

 torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
# convert torch tensor to numpy array
a = torch.ones(5)
print a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [16]:
b = a.numpy()
print b

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print a
print b


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[2. 2. 2. 2. 2.]


In [18]:
# convert numpy array to torch tensor

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [19]:
print torch.cuda.is_available()

False


In [21]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y